VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Hoja16"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Private Sub Worksheet_Activate()
      
    ' Opcional: Ocultar encabezados de filas y columnas para que parezca una App
    ActiveWindow.DisplayHeadings = False
    ActiveWindow.DisplayGridlines = False
End Sub

